<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="7" total="8" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="SALAutoamtion" duration-ms="172167" started-at="2019-11-05T09:32:56Z" finished-at="2019-11-05T09:35:49Z">
    <groups>
    </groups>
    <test name="DemoAutomation" duration-ms="172167" started-at="2019-11-05T09:32:56Z" finished-at="2019-11-05T09:35:49Z">
      <class name="com.client.xenon.tests.P2PTestCases">
        <test-method status="PASS" signature="getLogininfo()[pri:0, instance:com.client.xenon.tests.P2PTestCases@2bdd8394]" name="getLogininfo" is-config="true" duration-ms="840" started-at="2019-11-05T15:02:56Z" finished-at="2019-11-05T15:02:57Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getLogininfo -->
        <test-method status="FAIL" signature="createNoncatalogRequisition()[pri:5, instance:com.client.xenon.tests.P2PTestCases@2bdd8394]" name="createNoncatalogRequisition" duration-ms="169895" started-at="2019-11-05T15:02:57Z" description="create Noncatalog Requisition" finished-at="2019-11-05T15:05:47Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Element is not found.]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Element is not found.
	at org.testng.Assert.fail(Assert.java:94)
	at com.xenon.utility.selenium.Elements.clickMethod(Elements.java:244)
	at com.xenon.utility.selenium.Elements.click(Elements.java:233)
	at com.client.xenon.operations.P2POperations.createNoncatalogRequisition(P2POperations.java:101)
	at com.client.xenon.tests.P2PTestCases.createNoncatalogRequisition(P2PTestCases.java:45)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at com.xenon.core.framework.Xenon.excute(Xenon.java:154)
	at com.client.xenon.framework.DemoAutomation.main(DemoAutomation.java:15)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- createNoncatalogRequisition -->
      </class> <!-- com.client.xenon.tests.P2PTestCases -->
    </test> <!-- DemoAutomation -->
  </suite> <!-- SALAutoamtion -->
</testng-results>
